services:
  server:
    build:
      context: .
    environment:
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_SCHEMA: ${MYSQL_SCHEMA}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      SALT: ${SALT}
      SECRET: ${SECRET}
      ACCESS_TOKEN_EXPIRY_TIME: ${ACCESS_TOKEN_EXPIRY_TIME}
      REFRESH_TOKEN_EXPIRY_TIME: ${REFRESH_TOKEN_EXPIRY_TIME}
      VERIFY_TOKEN_EXPIRY_TIME: ${VERIFY_TOKEN_EXPIRY_TIME}
      PORT: ${PORT}
      URL: ${URL}
      MAILER_USER: ${MAILER_USER}
      MAILER_PASS: ${MAILER_PASS}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
    ports:
      - 3001:3001
