services:
  server:
    build:
      context: ..
    image: cistudy-server:latest
    container_name: main
    ports:
      - 3001:3001
    volumes:
      - storage:/usr/src/app/storage
      - tasks:/usr/src/app/tasks
volumes:
    storage:
    tasks:
 