services:
  server:
    build:
      context: ..
    image: cistudy-server:latest
    container_name: main
    environment:
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_SCHEMA: ${MYSQL_SCHEMA}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      SALT: ${SALT}
      SECRET: ${SECRET}
      ACCESS_TOKEN_EXPIRY_TIME: ${ACCESS_TOKEN_EXPIRY_TIME}
      REFRESH_TOKEN_EXPIRY_TIME: ${REFRESH_TOKEN_EXPIRY_TIME}
      VERIFY_TOKEN_EXPIRY_TIME: ${VERIFY_TOKEN_EXPIRY_TIME}
      PORT: ${PORT}
      URL: ${URL}
      MAILER_USER: ${MAILER_USER}
      MAILER_PASS: ${MAILER_PASS}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      EVM_PRIVATE_KEY: ${EVM_PRIVATE_KEY}
      EVM_ADDRESS: ${EVM_ADDRESS}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
    ports:
      - 3001:3001
    volumes:
      - storage:/usr/src/app/storage
      - tasks:/usr/src/app/tasks
volumes:
    storage:
    tasks: