type AuthTokens {
  accessToken: String!
  refreshToken: String!
}

type ResourceEntity {
  resourceId: ID!
  name: String!
  fileId: String!
  lectureId: ID!
  createdAt: DateTime!
  updatedAt: DateTime!
  lecture: LectureEntity!
}

"""
A date-time string at UTC, such as 2019-12-03T09:54:33Z, compliant with the date-time format.
"""
scalar DateTime

type LectureEntity {
  lectureId: ID!
  title: String!
  thumbnailId: ID
  lectureVideoId: ID
  sectionId: ID!
  processStatus: ProcessStatus!
  videoType: VideoType!
  createdAt: DateTime!
  updatedAt: DateTime!
  section: SectionEntity!
  resources: [ResourceEntity!]!
}

enum ProcessStatus {
  Pending
  Processing
  Completed
}

enum VideoType {
  MP4
  DASH
}

type SectionEntity {
  sectionId: ID!
  title: String!
  courseId: ID!
  createdAt: DateTime!
  course: CourseEntity!
  lectures: [LectureEntity!]!
}

type CourseTargetEntity {
  courseTargetId: ID!
  content: String!
  position: Float!
  createdAt: DateTime!
  updatedAt: DateTime!
  courseId: ID!
  course: CourseEntity!
}

type CourseEntity {
  courseId: ID!
  title: String!
  thumbnailId: ID
  description: String!
  creatorId: ID!
  price: Float!
  verifyStatus: VerifyStatus
  isDraft: Boolean!
  creator: UserEntity!
  isDeleted: Boolean!
  previewVideoId: ID
  includes: String
  courseTargets: [CourseTargetEntity!]
  sections: [SectionEntity!]!
}

enum VerifyStatus {
  Pending
  Approved
  Rejected
}

type PostReactEntity {
  postReactId: ID!
  userId: String!
  postId: String!
  liked: Boolean!
  createdAt: DateTime!
  updatedAt: DateTime!
  user: UserEntity!
  post: PostEntity!
}

type PostMediaEntity {
  postMediaId: ID!
  position: Int!
  mediaId: ID!
  postId: ID!
  mediaType: String!
  post: PostEntity!
}

type PostEntity {
  postId: ID!
  title: String!
  creatorId: ID!
  courseId: ID!
  createdAt: DateTime!
  updatedAt: DateTime!
  html: String!
  creator: UserEntity!
  postMedias: [PostMediaEntity!]!
  postComments: [PostCommentEntity!]!
  postReacts: [PostReactEntity!]!
}

type PostCommentMediaEntity {
  postCommentMediaId: ID!
  position: Int!
  mediaId: ID!
  postCommentId: String!
  mediaType: String!
  postComment: PostCommentEntity!
}

type PostCommentEntity {
  postCommentId: ID!
  creatorId: ID!
  postId: ID!
  createdAt: DateTime!
  updatedAt: DateTime!
  html: String!
  post: PostEntity!
  creator: UserEntity!
  postCommentMedias: [PostCommentMediaEntity!]!
}

type UserEntity {
  userId: ID!
  email: String!
  password: String
  avatarId: ID
  coverPhotoId: ID
  phoneNumber: String
  balance: Float
  role: UserRole!
  walletId: ID
  firstName: String
  lastName: String
  birthdate: DateTime
  verified: Boolean!
  kind: UserKind!
  externalId: String
}

enum UserRole {
  User
  Moderator
  Administrator
}

enum UserKind {
  Local
  Google
  Facebook
}

type FindOnePostOutput {
  data: PostEntity!
  tokens: AuthTokens
}

type FindManyPostsOutput {
  data: [PostEntity!]!
  tokens: AuthTokens
}

type FindOnePostCommentOutput {
  data: PostCommentEntity!
  tokens: AuthTokens
}

type InitOutput {
  data: UserEntity!
  tokens: AuthTokens
}

type SignInOutput {
  data: UserEntity!
  tokens: AuthTokens
}

type Query {
  init: InitOutput!
  signIn(data: SignInData!): SignInOutput!
  findOneCourse(data: FindOneCourseData!): CourseEntity!
  findManyCourses(data: FindManyCoursesData): [CourseEntity!]!
  findOnePost(data: FindOnePostData!): FindOnePostOutput!
  findOnePostComment(data: FindOnePostCommentData!): FindOnePostCommentOutput!
  findManyPosts(data: FindManyPostsData!): FindManyPostsOutput!
  findOneUser(data: FindOneUserData!): UserEntity!
}

input SignInData {
  email: String!
  password: String!
}

input FindOneCourseData {
  courseId: ID!
}

input FindManyCoursesData {
  filter: CourseFilterInput
}

input CourseFilterInput {
  category: String
}

input FindOnePostData {
  postId: ID!
}

input FindOnePostCommentData {
  postCommentId: ID!
}

input FindManyPostsData {
  courseId: String!
  options: FindManyPostsOptions
}

input FindManyPostsOptions {
  take: Int
  skip: Int
}

input FindOneUserData {
  userId: String!
}