type AuthTokens {
  accessToken: String!
  refreshToken: String!
}

type SectionEntity {
  sectionId: ID!
  title: String!
  courseId: ID!
  createdAt: DateTime!
  updatedAt: DateTime!
  course: CourseEntity!
  lessons: [LessonEntity!]
}

"""
A date-time string at UTC, such as 2019-12-03T09:54:33Z, compliant with the date-time format.
"""
scalar DateTime

type ResourceEntity {
  resourceId: ID!
  name: String!
  fileId: String!
  lessonId: ID!
  createdAt: DateTime!
  updatedAt: DateTime!
  lesson: LessonEntity!
}

type QuizAttemptAnswerEntity {
  quizAttemptAnswerId: ID!
  quizAttemptId: ID!
  quizQuestionAnswerId: ID!
  createdAt: DateTime!
  updatedAt: DateTime!
  quizAttempt: QuizAttemptEntity!
  quizQuestionAnswer: QuizQuestionAnswerEntity!
}

type QuizAttemptEntity {
  quizAttemptId: ID!
  quizId: ID!
  accountId: ID!
  score: Float
  attemptStatus: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  account: AccountEntity!
  quiz: QuizEntity!
  questionAnswers: [QuizQuestionAnswerEntity!]!
  attemptAnswers: [QuizAttemptAnswerEntity!]!
}

type QuizQuestionAnswerEntity {
  quizQuestionAnswerId: ID!
  quizQuestionId: ID!
  content: String!
  isCorrect: Boolean!
  quizQuestion: [QuizQuestionEntity!]!
  attemptAnswers: QuizAttemptAnswerEntity!
  createdAt: DateTime!
  updatedAt: DateTime!
  attempt: QuizAttemptEntity!
}

type QuizQuestionMediaEntity {
  quizQuestionMediaId: ID!
  position: Int!
  mediaId: ID!
  quizQuestionId: ID!
  mediaType: String!
  quiz: QuizQuestionEntity!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type QuizQuestionEntity {
  quizQuestionId: ID!
  quizId: ID!
  point: Float
  question: String!
  questionMedias: [QuizQuestionMediaEntity!]
  answers: [QuizQuestionAnswerEntity!]!
  createdAt: DateTime!
  updatedAt: DateTime!
  quiz: QuizEntity!
}

type QuizEntity {
  quizId: ID!
  questions: [QuizQuestionEntity!]!
  timeLimit: Int
  createdAt: DateTime!
  updatedAt: DateTime!
  lesson: LessonEntity!
  quizAttempts: QuizAttemptEntity!
  totalNumberOfAttempts: Int
  highestScoreRecorded: Float
}

type LessonEntity {
  lessonId: ID!
  title: String!
  thumbnailId: ID
  lessonVideoId: ID
  sectionId: ID!
  processStatus: String!
  videoType: String!
  numberOfViews: Int!
  description: String
  createdAt: DateTime!
  updatedAt: DateTime!
  section: SectionEntity!
  resources: [ResourceEntity!]!
  quiz: QuizEntity
  accountProgresses: [ProgressEntity!]!
}

type ProgressEntity {
  progressId: ID!
  enrolledInfoId: ID!
  lessonId: ID!
  isCompleted: Boolean!
  lesson: LessonEntity!
  enrolledInfo: EnrolledInfoEntity!
}

type EnrolledInfoEntity {
  enrolledInfoId: ID!
  accountId: ID!
  courseId: ID!
  endDate: DateTime
  createdAt: DateTime!
  updatedAt: DateTime!
  enrolled: Boolean!
  priceAtEnrolled: Float
  course: CourseEntity!
  account: AccountEntity!
  courseProgress: [ProgressEntity!]!
}

type CourseTargetEntity {
  courseTargetId: ID!
  content: String!
  position: Float!
  createdAt: DateTime!
  updatedAt: DateTime!
  courseId: ID!
  course: CourseEntity!
}

type CourseReviewEntity {
  courseReviewId: ID!
  courseId: ID!
  accountId: ID!
  content: String
  rating: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
  course: CourseEntity!
  account: AccountEntity
}

type CartEntity {
  cartId: ID!
  cartCourses: [CartCourseEntity!]
  isDeleted: Boolean!
  createdAt: DateTime!
  updatedAt: DateTime!
  account: AccountEntity
}

type CartCourseEntity {
  cartCourseId: ID!
  cartId: ID!
  courseId: ID!
  createdAt: DateTime!
  updatedAt: DateTime!
  course: CourseEntity!
  cart: CartEntity!
}

type CertificateEntity {
  certificateId: ID!
  courseId: ID!
  accountId: ID!
  createdAt: DateTime!
  achievedDate: DateTime
  expireDate: DateTime
  account: AccountEntity!
  course: CourseEntity
}

type OrderEntity {
  orderId: ID!
  accountId: ID!
  orderStatus: String!
  orderCourses: [OrderCourseEntity!]
  createdAt: DateTime!
  completeDate: DateTime
  updatedAt: DateTime!
  paymentDue: DateTime
  isDeleted: Boolean!
  account: AccountEntity!
}

type OrderCourseEntity {
  orderCourseId: ID!
  courseId: ID!
  orderId: ID!
  discountedPrice: Float!
  price: Float!
  createdAt: DateTime!
  updatedAt: DateTime!
  order: OrderEntity!
  course: CourseEntity!
}

type CategoryRelationEntity {
  categoryRelationId: ID!
  createdAt: DateTime!
  updatedAt: DateTime!
  categoryId: ID!
  categoryParentId: ID!
  category: CategoryEntity
  categoryParent: CategoryEntity
}

type CategoryEntity {
  categoryId: ID!
  level: Int!
  name: String
  imageId: ID
  createdAt: DateTime!
  updatedAt: DateTime!
  courseCategories: [CourseCategoryEntity!]
  categoryParentRelations: [CategoryRelationEntity!]
  categoryRelations: [CategoryRelationEntity!]
}

type CourseCategoryEntity {
  courseCategoryId: ID!
  courseId: ID!
  categoryId: ID!
  createdAt: DateTime!
  updatedAt: DateTime!
  course: CourseEntity!
  category: CategoryEntity
}

type ReportCourseEntity {
  reportCourseId: ID!
  reporterAccountId: ID!
  reportedCourseId: ID!
  title: String
  description: String
  processStatus: String!
  processNote: String
  createdAt: DateTime!
  updatedAt: DateTime!
  reporterAccount: AccountEntity!
  reportedCourse: CourseEntity!
}

type CourseRatingDTO {
  overallCourseRating: Float
  totalNumberOfRatings: Int
  numberOf1StarRatings: Int
  numberOf2StarRatings: Int
  numberOf3StarRatings: Int
  numberOf4StarRatings: Int
  numberOf5StarRatings: Int
}

type CourseCategoryLevelDTO {
  level0Categories: [CategoryEntity!]
  level1Categories: [CategoryEntity!]
  level2Categories: [CategoryEntity!]
}

type CourseEntity {
  courseId: ID!
  title: String
  thumbnailId: ID
  description: String
  creatorId: ID!
  price: Float!
  discountPrice: Float!
  enableDiscount: Boolean!
  verifyStatus: String!
  creator: AccountEntity!
  isDeleted: Boolean!
  receivedWalletAddress: String
  previewVideoId: ID
  includes: String
  duration: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
  courseCategories: [CourseCategoryEntity!]
  courseTargets: [CourseTargetEntity!]
  posts: [PostEntity!]
  sections: [SectionEntity!]
  cartCourses: [CartCourseEntity!]!
  certificate: [CertificateEntity!]!
  orderCourses: [OrderCourseEntity!]!
  courseReview: [CourseReviewEntity!]
  courseReports: [ReportCourseEntity!]
  numberOfEnrollments: Int
  enrolled: Boolean
  courseProgress: Float
  numberOfRewardedPostsLeft: Int
  courseRatings: CourseRatingDTO
  courseCategoryLevels: CourseCategoryLevelDTO
}

type PostLikeEntity {
  postLikeId: ID!
  accountId: String!
  postId: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  account: AccountEntity!
  post: PostEntity!
}

type PostMediaEntity {
  postMediaId: ID!
  position: Int!
  mediaId: ID!
  postId: ID!
  mediaType: String!
  post: PostEntity!
}

type ReportPostEntity {
  reportPostId: ID!
  reporterAccountId: ID!
  reportedPostId: ID!
  title: String
  description: String
  processStatus: String!
  processNote: String
  createdAt: DateTime!
  updatedAt: DateTime!
  reporterAccount: AccountEntity!
  reportedPost: PostEntity!
}

type PostEntity {
  postId: ID!
  title: String!
  creatorId: ID!
  courseId: ID!
  isCompleted: Boolean!
  isRewardable: Boolean!
  createdAt: DateTime!
  updatedAt: DateTime!
  html: String!
  course: CourseEntity!
  creator: AccountEntity!
  postMedias: [PostMediaEntity!]!
  postComments: [PostCommentEntity!]
  postReacts: [PostLikeEntity!]!
  postReports: [ReportPostEntity!]!
  liked: Boolean
  isPostOwner: Boolean
  numberOfLikes: Int
  numberOfComments: Int
  numberOfRewardableLikesLeft: Int
  numberOfRewardableCommentsLeft: Int
}

type PostCommentMediaEntity {
  postCommentMediaId: ID!
  position: Int!
  mediaId: ID!
  postCommentId: String!
  mediaType: String!
  postComment: PostCommentEntity!
}

type PostCommentReplyEntity {
  postCommentReplyId: ID!
  creatorId: ID!
  postCommentId: ID!
  createdAt: DateTime!
  updatedAt: DateTime!
  content: String!
  postComment: PostEntity!
  creator: AccountEntity!
}

type ReportPostCommentEntity {
  reportPostCommentId: ID!
  reporterAccountId: ID!
  reportedPostCommentId: ID!
  title: String
  description: String
  processStatus: String!
  processNote: String
  createdAt: DateTime!
  updatedAt: DateTime!
  reporterAccount: AccountEntity!
  reportedPostComment: PostCommentEntity!
}

type PostCommentEntity {
  postCommentId: ID!
  creatorId: ID!
  postId: ID!
  createdAt: DateTime!
  updatedAt: DateTime!
  html: String!
  isSolution: Boolean!
  post: PostEntity!
  creator: AccountEntity!
  postCommentMedias: [PostCommentMediaEntity!]!
  postCommentReports: [ReportPostCommentEntity!]!
  numberOfLikes: Int
  numberOfReplies: Int
  liked: Boolean
  isCommentOwner: Boolean
  isRewardable: Boolean
}

type FollowEntity {
  followId: ID!
  followerId: String!
  followedAccountId: String!
  followed: Boolean!
  createdAt: DateTime!
  updatedAt: DateTime!
  follower: AccountEntity!
  followedAccount: AccountEntity!
}

type CryptoWalletEntity {
  cryptoWalletId: ID!
  address: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  accountId: ID!
  account: AccountEntity!
}

type AccountReviewEntity {
  accountReviewId: ID!
  accountId: ID!
  reviewedAccountId: ID!
  content: String
  rating: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
  account: AccountEntity!
  reviewedAccount: AccountEntity!
}

type RoleEntity {
  roleId: ID!
  accountId: ID!
  name: String!
  isDisabled: Boolean!
  createdAt: DateTime!
  updatedAt: DateTime!
  accountRoles: AccountEntity!
}

type ReportAccountEntity {
  reportAccountId: ID!
  reporterAccountId: ID!
  reportedAccountId: ID!
  title: String
  description: String
  processStatus: String!
  processNote: String
  createdAt: DateTime!
  updatedAt: DateTime!
  reporterAccount: AccountEntity!
  reportedAccount: AccountEntity!
}

type AccountRatingDTO {
  overallAccountRating: Float
  totalNumberOfRatings: Int
  numberOf1StarRatings: Int
  numberOf2StarRatings: Int
  numberOf3StarRatings: Int
  numberOf4StarRatings: Int
  numberOf5StarRatings: Int
}

type AccountEntity {
  accountId: ID!
  email: String!
  password: String
  avatarId: ID
  avatarUrl: String
  coverPhotoId: ID
  phoneNumber: String
  username: String
  balance: Float
  walletAddress: String
  firstName: String
  lastName: String
  birthdate: DateTime
  verified: Boolean!
  kind: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  externalId: String
  roles: [RoleEntity!]
  cryptoWallets: [CryptoWalletEntity!]!
  posts: [PostEntity!]!
  courses: [CourseEntity!]!
  followerRelations: [FollowEntity!]!
  followedAccountRelations: [FollowEntity!]!
  courseReview: [CourseReviewEntity!]
  cart: CartEntity
  orders: [OrderEntity!]!
  certificates: [CertificateEntity!]!
  quizAttempts: [QuizAttemptEntity!]!
  accountReviews: [AccountReviewEntity!]!
  selfReviews: [AccountReviewEntity!]!
  reportAccounts: [ReportAccountEntity!]!
  accountReports: [ReportAccountEntity!]!
  followed: Boolean!
  numberOfFollowers: Int!
  accountRatings: AccountRatingDTO
}

type TransactionMongoEntity {
  transactionHash: String!
  from: String!
  to: String!
  value: String!
  isValidated: Boolean
  createdAt: DateTime!
  updatedAt: DateTime!
}

type FindManyCoursesOutputMetadata {
  count: Int
  categories: [CategoryEntity!]
  highRateCourses: [CourseEntity!]
}

type FindManyCoursesOutputData {
  results: [CourseEntity!]!
  metadata: FindManyCoursesOutputMetadata
}

type FindOneCourseAuthOutput {
  data: CourseEntity!
  tokens: AuthTokens
}

type FindOneLessonOutput {
  data: LessonEntity!
  tokens: AuthTokens
}

type FindManyLessonsOutput {
  data: [LessonEntity!]!
  tokens: AuthTokens
}

type FindManyResourcesOutput {
  data: [ResourceEntity!]!
  tokens: AuthTokens
}

type FindManyCourseTargetsOutput {
  data: [CourseTargetEntity!]!
  tokens: AuthTokens
}

type FindManyCourseReviewsOutputMetadata {
  count: Int
}

type FindManyCourseReviewsOutputData {
  results: [CourseReviewEntity!]!
  metadata: FindManyCourseReviewsOutputMetadata
}

type FindManyCoursesTopicOutputMetadata {
  count: Int
}

type FindManyCoursesTopicOutputData {
  results: [CourseEntity!]!
  metadata: FindManyCoursesTopicOutputMetadata
}

type FindOneQuizAttemptOutput {
  data: QuizAttemptEntity!
  tokens: AuthTokens
  numberOfQuestions: Int
}

type FindManyCourseReportsOutputMetadata {
  count: Int
}

type FindManyCourseReportsOutputData {
  results: [ReportCourseEntity!]!
  metadata: FindManyCourseReportsOutputMetadata
}

type FindManyCourseReportsOutput {
  data: FindManyCourseReportsOutputData!
  tokens: AuthTokens
}

type FindOnePostOutput {
  data: PostEntity!
  tokens: AuthTokens
}

type FindManyPostsOutputMetadata {
  count: Int
}

type FindManyPostsOutputData {
  results: [PostEntity!]!
  metadata: FindManyPostsOutputMetadata
}

type FindManyPostsOutput {
  data: FindManyPostsOutputData!
  tokens: AuthTokens
}

type FindOnePostCommentOutputMetadata {
  count: Int
}

type FindOnePostCommentOutput {
  data: PostCommentEntity!
  tokens: AuthTokens
}

type FindManyPostCommentsOutputData {
  results: [PostCommentEntity!]!
  metadata: FindOnePostCommentOutputMetadata
}

type FindManyPostCommentsOutput {
  data: FindManyPostCommentsOutputData!
  tokens: AuthTokens
}

type FindManyPostCommentRepliesOutputData {
  results: [PostCommentReplyEntity!]!
  metadata: FindOnePostCommentOutputMetadata
}

type FindManyPostCommentRepliesOutput {
  data: FindManyPostCommentRepliesOutputData!
  tokens: AuthTokens
}

type FindManyPostReportsOutputMetadata {
  count: Int
}

type FindManyPostReportsOutputData {
  results: [ReportPostEntity!]!
  metadata: FindManyPostReportsOutputMetadata
}

type FindManyPostReportsOutput {
  data: FindManyPostReportsOutputData!
  tokens: AuthTokens
}

type FindManyPostCommentReportsOutputMetadata {
  count: Int
}

type FindManyPostCommentReportsOutputData {
  results: [ReportPostCommentEntity!]!
  metadata: FindManyPostCommentReportsOutputMetadata
}

type FindManyPostCommentReportsOutput {
  data: FindManyPostCommentReportsOutputData!
  tokens: AuthTokens
}

type FindManyAccountsOutputMetadata {
  count: Int
}

type FindManyAccountsOutputData {
  results: [AccountEntity!]!
  metadata: FindManyAccountsOutputMetadata
}

type FindManyAccountsOutput {
  data: FindManyAccountsOutputData!
  tokens: AuthTokens
}

type FindManyAccountReviewsOutputMetadata {
  count: Int
}

type FindManyAccountReviewsOutputData {
  results: [AccountReviewEntity!]!
  metadata: FindManyAccountReviewsOutputMetadata
}

type FindManyAccountReportsOutputMetadata {
  count: Int
}

type FindManyAccountReportsOutputData {
  results: [ReportAccountEntity!]!
  metadata: FindManyAccountReportsOutputMetadata
}

type FindManyAccountReportsOutput {
  data: FindManyAccountReportsOutputData!
  tokens: AuthTokens
}

type FindManyUnverifiedCourseOutputMetadata {
  count: Int
}

type FindManyUnverifiedCourseOutputData {
  results: [CourseEntity!]!
  metadata: FindManyUnverifiedCourseOutputMetadata!
}

type FindManyUnverifiedCourseOutput {
  data: FindManyUnverifiedCourseOutputData!
  tokens: AuthTokens
}

type FindManySelfCreatedCoursesOutputMetadata {
  count: Int
}

type FindManySelfCreatedCoursesOutputData {
  results: [CourseEntity!]!
  metadata: FindManySelfCreatedCoursesOutputMetadata
}

type FindManySelfCreatedCoursesOutput {
  data: FindManySelfCreatedCoursesOutputData!
  tokens: AuthTokens
}

type FindManyEnrolledCoursesOutputMetadata {
  count: Int
}

type FindManyEnrolledCoursesOutputData {
  results: [CourseEntity!]!
  metadata: FindManyEnrolledCoursesOutputMetadata
}

type FindManyEnrolledCoursesOutput {
  data: FindManyEnrolledCoursesOutputData!
  tokens: AuthTokens
}

type InitOutput {
  data: AccountEntity!
  tokens: AuthTokens
}

type SignInOutput {
  tokens: AuthTokens
}

type VerifyGoogleAccessTokenOutput {
  data: AccountEntity!
  tokens: AuthTokens
}

type InitLandingPageOutputOthers {
  totalNumberOfVerifiedAccounts: Int
  totalNumberOfAvailableCourses: Int
  totalNumberOfPosts: Int
  mostEnrolledCourses: [CourseEntity!]
  highRatedCourses: [CourseEntity!]
  highRatedInstructors: [AccountEntity!]
  recentlyAddedCourses: [CourseEntity!]
}

type FindManyTransactionsOutputMetadata {
  count: Int
}

type FindManyTransactionsOutput {
  results: [TransactionMongoEntity!]!
  metadata: FindManyTransactionsOutputMetadata
}

type FindOneCartOutput {
  data: CartEntity!
  tokens: AuthTokens
}

type FindOneOrderOutput {
  data: OrderEntity!
  tokens: AuthTokens
}

type FindManyAccountOrdersOutputMetadata {
  count: Int
}

type FindManyAccountOrdersOutputData {
  results: [OrderEntity!]!
  metadata: FindManyAccountOrdersOutputMetadata
}

type FindManyAccountOrdersOutput {
  data: FindManyAccountOrdersOutputData!
  tokens: AuthTokens
}

type Query {
  init: InitOutput!
  initLandingPage: InitLandingPageOutputOthers!
  signIn(data: SignInInputData!): SignInOutput!
  verifyGoogleAccessToken(data: VerifyGoogleAccessTokenData!): VerifyGoogleAccessTokenOutput!
  findOneCourse(data: FindOneCourseInputData!): CourseEntity!
  findOneCourseAuth(data: FindOneCourseAuthInputData!): FindOneCourseAuthOutput!
  findManyCourses(data: FindManyCoursesInputData!): FindManyCoursesOutputData!
  findOneLesson(data: FindOneLessonInputData!): FindOneLessonOutput!
  findManyLessons(data: FindManyLessonsInputData!): FindManyLessonsOutput!
  findManyResources(data: FindManyResourcesInputData!): FindManyResourcesOutput!
  findManyCourseTargets(data: FindManyCourseTargetsInputData!): FindManyCourseTargetsOutput!
  findOneCourseReview(data: FindOneCourseReviewInputData!): CourseReviewEntity!
  findManyCourseReviews(data: FindManyCourseReviewsInputData!): FindManyCourseReviewsOutputData!
  findManyCoursesTopic(data: FindManyCoursesTopicInputData!): FindManyCoursesTopicOutputData!
  findOneQuizAttempt(data: FindOneQuizAttemptInputData!): FindOneQuizAttemptOutput!
  findManyLevelCategories(data: FindManyLevelCategoriesInputData!): [CategoryEntity!]!
  findManyCategories: [CategoryEntity!]!
  findManyCourseReports(data: FindManyCourseReportsInputData!): FindManyCourseReportsOutput!
  findOnePost(data: FindOnePostInputData!): FindOnePostOutput!
  findManyPosts(data: FindManyPostsInputData!): FindManyPostsOutput!
  findOnePostComment(data: FindOnePostCommentInputData!): FindOnePostCommentOutput!
  findManyPostComments(data: FindManyPostCommentsInputData!): FindManyPostCommentsOutput!
  findManyPostCommentReplies(data: FindManyPostCommentRepliesInputData!): FindManyPostCommentRepliesOutput!
  findManyPostReports(data: FindManyPostReportsInputData!): FindManyPostReportsOutput!
  findManyPostCommentReports(data: FindManyPostCommentReportsInputData!): FindManyPostCommentReportsOutput!
  findOneAccount(data: FindOneAccountInputData!): AccountEntity!
  findManyFollowers(data: FindManyFollowersInputData!): [AccountEntity!]!
  findManyAccounts(data: FindManyAccountsInputData!): FindManyAccountsOutput!
  findManyAccountReviews(data: FindManyAccountReviewsInputData!): FindManyAccountReviewsOutputData!
  findManyAccountReports(data: FindManyAccountReportsInputData!): FindManyAccountReportsOutput!
  findManyUnverifiedCourses(data: FindManyUnverifiedCourseInputData!): FindManyUnverifiedCourseOutput!
  findManySelfCreatedCourses(data: FindManySelfCreatedCoursesInputData!): FindManySelfCreatedCoursesOutput!
  findManyEnrolledCourses(data: FindManyEnrolledCoursesInputData!): FindManyEnrolledCoursesOutput!
  findManyTransactions(data: FindManyTransactionsInputData!): FindManyTransactionsOutput!
  findOneCart: FindOneCartOutput!
  findOneOrder(data: FindOneOrderInputData!): FindOneOrderOutput!
  findManyAccountOrders(data: FindManyAccountOrdersInputData!): FindManyAccountOrdersOutput!
}

input SignInInputData {
  params: SignInInputParams!
}

input SignInInputParams {
  email: String!
  password: String!
}

input VerifyGoogleAccessTokenData {
  params: VerifyGoogleAccessTokenParams!
}

input VerifyGoogleAccessTokenParams {
  token: ID!
}

input FindOneCourseInputData {
  params: FindOneCourseInputParams!
}

input FindOneCourseInputParams {
  courseId: ID!
  accountId: ID
}

input FindOneCourseAuthInputData {
  params: FindOneCourseAuthInputParams!
}

input FindOneCourseAuthInputParams {
  courseId: ID!
}

input FindManyCoursesInputData {
  options: FindManyCoursesInputOptions
}

input FindManyCoursesInputOptions {
  take: Int
  skip: Int
  searchValue: String
  categoryId: String
}

input FindOneLessonInputData {
  params: FindOneLessonInputParams!
  options: FindOneLessonInputOptions
}

input FindOneLessonInputParams {
  lessonId: ID!
}

input FindOneLessonInputOptions {
  followerId: ID
}

input FindManyLessonsInputData {
  params: FindManyLessonsInputParams!
}

input FindManyLessonsInputParams {
  sectionId: ID!
}

input FindManyResourcesInputData {
  params: FindManyResourcesInputParams!
}

input FindManyResourcesInputParams {
  lessonId: ID!
}

input FindManyCourseTargetsInputData {
  params: FindManyCourseTargetsInputParams!
}

input FindManyCourseTargetsInputParams {
  courseId: ID!
}

input FindOneCourseReviewInputData {
  params: FindOneCourseReviewInputParams!
}

input FindOneCourseReviewInputParams {
  courseId: ID!
}

input FindManyCourseReviewsInputData {
  params: FindManyCourseReviewsInputParams!
  options: FindManyCourseReviewsInputOptions
}

input FindManyCourseReviewsInputParams {
  courseId: ID!
}

input FindManyCourseReviewsInputOptions {
  take: Int
  skip: Int
}

input FindManyCoursesTopicInputData {
  params: FindManyCoursesTopicInputParams!
  options: FindManyCoursesTopicInputOptions
}

input FindManyCoursesTopicInputParams {
  topicId: ID!
}

input FindManyCoursesTopicInputOptions {
  take: Int
  skip: Int
}

input FindOneQuizAttemptInputData {
  params: FindOneQuizAttemptInputParams!
  options: FindOneQuizAttemptInputOptions!
}

input FindOneQuizAttemptInputParams {
  quizAttemptId: String!
}

input FindOneQuizAttemptInputOptions {
  take: Int
  skip: Int
}

input FindManyLevelCategoriesInputData {
  categoryParentId: ID
}

input FindManyCourseReportsInputData {
  options: FindManyCourseReportsInputOptions
}

input FindManyCourseReportsInputOptions {
  take: Int
  skip: Int
}

input FindOnePostInputData {
  params: FindOnePostInputParams!
}

input FindOnePostInputParams {
  postId: ID!
}

input FindManyPostsInputData {
  params: FindManyPostsInputParams!
  options: FindManyPostsInputOptions
}

input FindManyPostsInputParams {
  courseId: String!
}

input FindManyPostsInputOptions {
  take: Int
  skip: Int
}

input FindOnePostCommentInputData {
  params: FindOnePostCommentInputParams!
}

input FindOnePostCommentInputParams {
  postCommentId: ID!
}

input FindManyPostCommentsInputData {
  params: FindManyPostCommentsInputParams!
  options: FindManyPostCommentsInputOptions
}

input FindManyPostCommentsInputParams {
  postId: String!
}

input FindManyPostCommentsInputOptions {
  take: Int
  skip: Int
}

input FindManyPostCommentRepliesInputData {
  params: FindManyPostCommentRepliesInputParams!
  options: FindManyPostsCommentRepliesInputOptions
}

input FindManyPostCommentRepliesInputParams {
  postCommentId: String!
}

input FindManyPostsCommentRepliesInputOptions {
  take: Int
  skip: Int
}

input FindManyPostReportsInputData {
  options: FindManyPostReportsInputOptions
}

input FindManyPostReportsInputOptions {
  take: Int
  skip: Int
}

input FindManyPostCommentReportsInputData {
  options: FindManyPostCommentReportsInputOptions
}

input FindManyPostCommentReportsInputOptions {
  take: Int
  skip: Int
}

input FindOneAccountInputData {
  params: FindOneAccountInputParams!
  options: FindOneAccountInputOptions
}

input FindOneAccountInputParams {
  accountId: ID!
}

input FindOneAccountInputOptions {
  followerId: ID
}

input FindManyFollowersInputData {
  params: FindManyFollowersInputParams!
}

input FindManyFollowersInputParams {
  accountId: ID!
}

input FindManyAccountsInputData {
  options: FindManyAccountsInputOptions
}

input FindManyAccountsInputOptions {
  take: Int
  skip: Int
  searchValue: String
}

input FindManyAccountReviewsInputData {
  params: FindManyAccountReviewsInputParams!
  options: FindManyAccountReviewsInputOptions
}

input FindManyAccountReviewsInputParams {
  accountId: ID!
}

input FindManyAccountReviewsInputOptions {
  take: Int
  skip: Int
}

input FindManyAccountReportsInputData {
  options: FindManyAccountReportsInputOptions
}

input FindManyAccountReportsInputOptions {
  take: Int
  skip: Int
}

input FindManyUnverifiedCourseInputData {
  options: FindManyUnverifiedCourseInputOptions
}

input FindManyUnverifiedCourseInputOptions {
  take: Int
  skip: Int
}

input FindManySelfCreatedCoursesInputData {
  options: FindManySelfCreatedCoursesInputOptions
}

input FindManySelfCreatedCoursesInputOptions {
  take: Int
  skip: Int
}

input FindManyEnrolledCoursesInputData {
  options: FindManyEnrolledCoursesInputOptions
}

input FindManyEnrolledCoursesInputOptions {
  take: Int
  skip: Int
}

input FindManyTransactionsInputData {
  options: FindManyTransactionsInputOptions
}

input FindManyTransactionsInputOptions {
  take: Int
  skip: Int
}

input FindOneOrderInputData {
  params: FindOneOrderInputParams!
}

input FindOneOrderInputParams {
  orderId: ID!
}

input FindManyAccountOrdersInputData {
  options: FindManyAccountOrdersInputOptions
}

input FindManyAccountOrdersInputOptions {
  take: Int
  skip: Int
  orderStatus: String!
}