name: Compose Docker project

on:
  push:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: self-hosted
    environment: docker
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 

    - name: Run Docker compose command
      env:
        MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_SCHEMA: ${{ secrets.MYSQL_SCHEMA }}
        MYSQL_HOST: ${{ vars.MYSQL_HOST }}
        MYSQL_PORT: ${{ vars.MYSQL_PORT }}
        REDIS_HOST: ${{ vars.REDIS_HOST }}
        REDIS_PORT: ${{ vars.REDIS_PORT }}
        SALT: ${{ secrets.SALT }}
        SECRET: ${{ secrets.SECRET }}
        ACCESS_TOKEN_EXPIRY_TIME: ${{ vars.ACCESS_TOKEN_EXPIRY_TIME }}
        REFRESH_TOKEN_EXPIRY_TIME: ${{ vars.REFRESH_TOKEN_EXPIRY_TIME }}
        VERIFY_TOKEN_EXPIRY_TIME: ${{ vars.VERIFY_TOKEN_EXPIRY_TIME }}
        PORT: ${{ vars.PORT }}
        URL: ${{ vars.URL }}
        MAILER_USER: ${{ secrets.MAILER_USER }}
        MAILER_PASS: ${{ secrets.MAILER_PASS }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
        FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
        SUPABASE_URL: ${{ vars.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: docker-compose -f docker/github-compose.yaml up --build
